sudo: required

language: bash

services:
  - docker

before_script:
  - export APP_IMAGE=keboola-wr-looker-v2
  - docker -v
  - docker build -t $APP_IMAGE .
  - docker run -e KBC_URL -e KBC_TOKEN -e SNOWFLAKE_BACKEND_CONFIG_ID -e SNOWFLAKE_BACKEND_DB_PASSWORD -e BIGQUERY_BACKEND_CONFIG_ID -e BIGQUERY_BACKEND_PRIVATE_KEY $APP_IMAGE composer ci
  # push test image to ECR
  - docker pull quay.io/keboola/developer-portal-cli-v2:latest
  - export REPOSITORY=`docker run --rm -e KBC_DEVELOPERPORTAL_USERNAME -e KBC_DEVELOPERPORTAL_PASSWORD -e KBC_DEVELOPERPORTAL_URL quay.io/keboola/developer-portal-cli-v2:latest ecr:get-repository $KBC_DEVELOPERPORTAL_VENDOR $KBC_DEVELOPERPORTAL_APP`
  - docker tag $APP_IMAGE:latest $REPOSITORY:test
  - eval $(docker run --rm -e KBC_DEVELOPERPORTAL_USERNAME -e KBC_DEVELOPERPORTAL_PASSWORD -e KBC_DEVELOPERPORTAL_URL quay.io/keboola/developer-portal-cli-v2:latest ecr:get-login $KBC_DEVELOPERPORTAL_VENDOR $KBC_DEVELOPERPORTAL_APP)
  - docker push $REPOSITORY:test
  - docker pull quay.io/keboola/syrup-cli:latest


script:
  # run test job inside KBC
  - export KBC_STORAGE_TOKEN=$KBC_TOKEN
  #- docker run --rm -e KBC_STORAGE_TOKEN quay.io/keboola/syrup-cli:latest run-job $KBC_DEVELOPERPORTAL_APP $SNOWFLAKE_BACKEND_CONFIG_ID test
  #- docker run --rm -e KBC_STORAGE_TOKEN quay.io/keboola/syrup-cli:latest run-job $KBC_DEVELOPERPORTAL_APP $BIGQUERY_BACKEND_CONFIG_ID test

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true
