version: '2'
services:
  dev: &default
    build:
      context: .
    image: looker_writer_v2_dev
    volumes:
      - ./:/code
      - ./data:/data

  dev-xdebug:
    <<: *default
    build:
      context: docker/xdebug
