version: '2'
services:
  dev: &default
    build:
      context: .
    image: looker_writer_v2_dev
    environment:
      - KBC_CONFIGID=12345
      - KBC_URL
      - KBC_TOKEN
    volumes:
      - ./:/code
      - ./data:/data

  dev-xdebug:
    <<: *default
    build:
      context: docker/xdebug
