version: '2'
services:
  dev: &default
    build:
      context: .
    image: looker_writer_v2_dev
    environment:
      - KBC_CONFIGID
      - KBC_URL
      - KBC_TOKEN
      - KBC_RUNID
      - SNOWFLAKE_BACKEND_CONFIG_ID
      - SNOWFLAKE_BACKEND_DB_PASSWORD
      - BIGQUERY_BACKEND_CONFIG_ID
      - BIGQUERY_BACKEND_PRIVATE_KEY
      - KBC_STAGING_FILE_PROVIDER
    volumes:
      - ./:/code
      - ./data:/data

  dev-xdebug:
    <<: *default
    depends_on:
      - dev
    build:
      context: docker/xdebug
